service: serverless-bolt-js
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
  hello:
    handler: app2.handler
    events:
      - http:
          path: /hello
          method: get
plugins:
  - serverless-offline
